# Generated by Django 3.2.12 on 2022-04-11 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='dateAdded',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
