# Generated by Django 3.2.12 on 2022-04-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_song_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='/images/default/placeholder.png', upload_to='images/genres/'),
        ),
    ]
