# Generated by Django 3.2.12 on 2022-04-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.CharField(max_length=11),
        ),
    ]
