# Generated by Django 3.2.12 on 2022-04-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_alter_song_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
    ]
