# Generated by Django 3.2.12 on 2022-04-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0003_alter_genre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='/images/default/placeholder.png', upload_to='images/genres/'),
        ),
    ]
