# Generated by Django 3.2.12 on 2022-04-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0005_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='clicks',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
