# Generated by Django 3.2.12 on 2022-04-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_alter_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='age',
        ),
    ]
