# Generated by Django 3.2.12 on 2022-04-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_artist_popularity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='popularity',
            new_name='clicks',
        ),
    ]
