# Generated by Django 4.0.3 on 2022-05-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_rename_popularity_artist_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='nationality',
        ),
    ]
